name: Manual Chained Jobs

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First message
        run: echo "Premier job déclenché manuellement"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Second message
        run: echo "Second job lancé après le premier"
